# Generated by Django 4.2.4 on 2023-08-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='customer_xid',
            new_name='customer',
        ),
    ]
