# Generated by Django 4.2.4 on 2023-08-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywallet', '0003_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='wallet',
            field=models.ForeignKey(default='e91c8061-76bb-4d87-b7ff-19a1ff452530', on_delete=django.db.models.deletion.CASCADE, to='mywallet.wallet'),
            preserve_default=False,
        ),
    ]
